# Generated by Django 5.2.5 on 2025-08-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_notification_news_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='news_category',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='news_content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='news_title',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='news', to='news.category'),
        ),
    ]
