# Generated by Django 5.2.4 on 2025-08-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(blank=True, max_length=120)),
                ('age_group', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('availability', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(blank=True, max_length=120)),
                ('age_group', models.CharField(blank=True, max_length=120)),
                ('timing', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('helpline_number', models.CharField(blank=True, max_length=30)),
                ('maps_url', models.URLField(blank=True)),
                ('type', models.CharField(choices=[('vaccination', 'Vaccination'), ('checkup', 'Health Checkup'), ('awareness', 'Awareness'), ('other', 'Other')], max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicines', models.ManyToManyField(blank=True, related_name='campaigns', to='campaigns.medicine')),
                ('vaccines', models.ManyToManyField(blank=True, related_name='campaigns', to='campaigns.vaccine')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
