# Generated by Django 5.2.5 on 2025-08-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineTracker', '0002_uservaccinerecord_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='dose_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Recommended days between doses (if applicable).', null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='max_doses',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='uservaccinerecord',
            name='date_given',
            field=models.DateField(blank=True, null=True),
        ),
    ]
