# Generated by Django 5.2.5 on 2025-08-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineTracker', '0003_vaccine_dose_interval_days_vaccine_max_doses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservaccinerecord',
            name='administered_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
