# Generated by Django 5.2.5 on 2025-08-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineTracker', '0004_alter_uservaccinerecord_administered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservaccinerecord',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='uservaccinerecord',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
